name: vhouseplanner
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # For making API requests to Flask
  image_picker: ^1.0.7  # To select images from the gallery or camera
  path_provider: ^2.1.2  # To store selected images locally
  file_picker: ^5.2.10 
  universal_html: ^2.2.4 
    
  image: ^4.0.17  # For image processing if needed
  provider: ^6.0.5  # For state management (if required)
  
  shared_preferences: ^2.2.0  # Optional: Store previous estimations locally

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
